server.port=9090

payment.api.base-url=http://localhost:8080
payment.api.store-id=coffee-place-downtown
sync.max-retries=3
sync.retry-backoff-ms=1000

# Metadata DB (non-sharded)
payment.datasource.metadata.url=jdbc:postgresql://postgres-metadata:5432/metadata
payment.datasource.metadata.username=user
payment.datasource.metadata.password=pass

# Sharded DBs
payment.shard.count=2
payment.shard.datasource.host-pattern=jdbc:postgresql://postgres-shard-%d:5432/payments
payment.shard.datasource.username=user
payment.shard.datasource.password=pass

# Async executor pool
payment.async.core-pool-size=4
payment.async.max-pool-size=8
